---
abstract: 'Write an Excel XML file.'
author:
  - 'John McNamara (jmcnamara@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spreadsheet-WriteExcelXML
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: http://github.com/jmcnamara/spreadsheet-writeexcelxml
  x_MailingList: http://groups.google.com/group/spreadsheet-writeexcel
version: 0.14
