--- #YAML:1.0
name:               Spreadsheet-WriteExcelXML
version:            0.11
abstract:           Write an Excel XML file.
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    MailingList:  http://groups.google.com/group/spreadsheet-writeexcel
    repository:   http://github.com/jmcnamara/spreadsheet-writeexcel
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
